apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
      - name: auth
        image: fatimaqurban/auth-deployment
        ports:
        - containerPort: 1195
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: auth-db-secret
              key: MONGODB_URL
