apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: client-service
spec:
  selector:
    app: client-service
  ports:
    - protocol: TCP
      port: 1198
      targetPort: 1198
  type: NodePort
