apiVersion: apps/v1
kind: Deployment
metadata:
  name: classroom-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: classroom-deployment
  template:
    metadata:
      labels:
        app: classroom-deployment
    spec:
      containers:
      - name: classroom
        image: fatimaqurban/classroom-deployment
        ports:
        - containerPort: 1196
        env:
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: classroom-db-secret
              key: MONGODB_URL
